### ISSUE TITLE
Call to a member function path() on null errors on Grav 1.7

### ISSUE THREAD

**Issue by thekenshow** [Perlkonig/grav-plugin-table-importer#20]
The table-importer plugin v2.2.1 works fine on Grav 1.6.16 but after upgrading to 1.7.x, it throws a `Call to a member function path() on null` error at `user/plugins/table-importer/TableImporterShortcode.php:166`.
 
The error does not occur if the individual page cache is disabled ( `cache_enable: false` ). The relevant page config is as follows:

```
title: 'My Tableimporter Page'
tablesorter:
    active: true
    raw: true
    tablenums: '1,2'
    include_widgets: true
    include_metadata: true
    themes: bootstrap
    args:
        1:
            theme: bootstrap
            widgets:
                - filter
                - zebra
        2:
            theme: bootstrap
            widgets:
                - filter
                - zebra
---
```

<img width="1242" alt="Screen Shot 2022-01-25 at 9 38 42 AM" src="https://user-images.githubusercontent.com/998832/151009945-652e838b-1eb2-4de2-9ecb-d36f9c638e60.png">
